version: '0.1'
services:
    postgres:
        image: postgres:14-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=parking
        ports:
          - '5432:5432'
        volumes: 
          - ./db/postgres-data:/var/lib/postgresql/data
          - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./db/seed.sql:/docker-entrypoint-initdb.d/fill_tables.sql